#### Installation check

In [1]:
import torch
print(torch.__version__)
print("GPU Available? {}".format(torch.cuda.is_available()))
print("CUDA Toolkit version: {}".format(torch.version.cuda))

0.4.1
GPU Available? True
CUDA Toolkit version: 9.0


#### Basic

In [5]:
import numpy as np
# Creating nd-array
x_cpu = torch.tensor([1,2,3])
z = np.random.randint(1, 9, (5,4))
y_cpu = torch.tensor(z)
print(x_cpu)
print(y_cpu)

# Transfer of tensor to GPU
x_gpu = x_cpu.cuda()
y_gpu = y_cpu.cuda()
print(x_gpu)
print(y_gpu)

tensor([1, 2, 3])
tensor([[2, 1, 6, 8],
        [2, 3, 7, 4],
        [5, 6, 4, 3],
        [4, 8, 4, 3],
        [7, 7, 4, 1]], dtype=torch.int32)
tensor([1, 2, 3], device='cuda:0')
tensor([[2, 1, 6, 8],
        [2, 3, 7, 4],
        [5, 6, 4, 3],
        [4, 8, 4, 3],
        [7, 7, 4, 1]], device='cuda:0', dtype=torch.int32)


In [9]:
# Shape and Reshape
x = x_gpu
y = y_gpu
print(x.shape, y.shape)

y.reshape(1,20)
print(y, y.shape)

y.reshape(4,5)
print(y, y.shape)

torch.Size([3]) torch.Size([5, 4])
tensor([[2, 1, 6, 8],
        [2, 3, 7, 4],
        [5, 6, 4, 3],
        [4, 8, 4, 3],
        [7, 7, 4, 1]], device='cuda:0', dtype=torch.int32) torch.Size([5, 4])
tensor([[2, 1, 6, 8],
        [2, 3, 7, 4],
        [5, 6, 4, 3],
        [4, 8, 4, 3],
        [7, 7, 4, 1]], device='cuda:0', dtype=torch.int32) torch.Size([5, 4])
