#### Installation check

In [1]:
import torch
print(torch.__version__)
print("GPU Available? {}".format(torch.cuda.is_available()))
print("CUDA Toolkit version: {}".format(torch.version.cuda))

0.4.1
GPU Available? True
CUDA Toolkit version: 9.0


#### Basic

In [2]:
import numpy as np
# Creating nd-array
x_cpu = torch.tensor([1,2,3]) #int (Factory function, better than torch.Tensor)
z = np.random.randint(1, 9, (5,4))
y_cpu = torch.tensor(z)
print(x_cpu)
print(y_cpu)

# Transfer of tensor to GPU
x_gpu = x_cpu.cuda()
y_gpu = y_cpu.cuda()
print(x_gpu)
print(y_gpu)

tensor([1, 2, 3])
tensor([[7, 6, 5, 3],
        [1, 3, 2, 4],
        [7, 5, 7, 4],
        [8, 3, 4, 3],
        [7, 1, 2, 3]], dtype=torch.int32)
tensor([1, 2, 3], device='cuda:0')
tensor([[7, 6, 5, 3],
        [1, 3, 2, 4],
        [7, 5, 7, 4],
        [8, 3, 4, 3],
        [7, 1, 2, 3]], device='cuda:0', dtype=torch.int32)


In [3]:
# Shape and Reshape
x = x_gpu
y = y_gpu
print(x.shape, y.shape)

y = y.reshape(1,20)
print(y, y.shape)

y = y.reshape(4,5)
print(y, y.shape)

torch.Size([3]) torch.Size([5, 4])
tensor([[7, 6, 5, 3, 1, 3, 2, 4, 7, 5, 7, 4, 8, 3, 4, 3, 7, 1, 2, 3]],
       device='cuda:0', dtype=torch.int32) torch.Size([1, 20])
tensor([[7, 6, 5, 3, 1],
        [3, 2, 4, 7, 5],
        [7, 4, 8, 3, 4],
        [3, 7, 1, 2, 3]], device='cuda:0', dtype=torch.int32) torch.Size([4, 5])


In [4]:
# tensor constructor
torch.Tensor()

tensor([])

In [5]:
torch.tensor(2,4)

TypeError: tensor() takes 1 positional argument but 2 were given

In [6]:
torch.Tensor(2,4)

tensor([[4.4721e+21, 2.8799e+32, 4.5713e+07, 3.9760e+12],
        [7.5338e+28, 1.5975e-43, 0.0000e+00, 0.0000e+00]])

In [11]:
t = torch.Tensor([1,2,3,4]) #float (Constructor)
t = t.cuda()
print(t.dtype)
print(t.device)
t

torch.float32
cuda:0


tensor([1., 2., 3., 4.], device='cuda:0')

In [12]:
print(torch.eye(3))
print(torch.zeros(3,2))
print(torch.ones(3,2))
print(torch.rand(3,2))
print(torch.randint(low=0, high=9, size=(3,2)))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0.9816, 0.1399],
        [0.5713, 0.5401],
        [0.7138, 0.3257]])
tensor([[2., 4.],
        [1., 2.],
        [0., 8.]])


In [13]:
torch.tensor([1,2,3], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [19]:
# Which tensor?
x = np.array([1,2,3])
t1 = torch.Tensor(x) #copy
t2 = torch.tensor(x) #--||-- best
t3 = torch.as_tensor(x) #share memory ... faster better for performance
t4 = torch.from_numpy(x) #--||--

print(t1, t2, t3, t4)
x[0] = 0
x[1] = 0
x[2] = 0
print(t1, t2, t3, t4)

tensor([1., 2., 3.]) tensor([1, 2, 3], dtype=torch.int32) tensor([1, 2, 3], dtype=torch.int32) tensor([1, 2, 3], dtype=torch.int32)
tensor([1., 2., 3.]) tensor([1, 2, 3], dtype=torch.int32) tensor([0, 0, 0], dtype=torch.int32) tensor([0, 0, 0], dtype=torch.int32)


In [20]:
# shape, size, num_dim, num_elements
t = torch.tensor(torch.randint(0,9,(3,4)))
print(t.shape)
print(t.size())
print(len(t.shape))
print(t.numel(), torch.tensor(t.shape).prod())

torch.Size([3, 4])
torch.Size([3, 4])
2
12 tensor(12)


In [25]:
# reshape, squeeze, unsqueeze 
print(t.reshape(12,1))
print(t.reshape(1,12))
print(t.reshape(4,3))
print(t.reshape(2,2,3))

print(t.reshape(12)) #similar to
print(t.reshape(12,1).squeeze()) #this #removes axis having length==1
print(t.reshape(12,1).squeeze().unsqueeze(dim=1)) #adds axis of length==1
print(t.reshape(12,1).squeeze().unsqueeze(dim=0))

tensor([[1.],
        [0.],
        [1.],
        [6.],
        [5.],
        [4.],
        [8.],
        [7.],
        [2.],
        [1.],
        [0.],
        [4.]])
tensor([[1., 0., 1., 6., 5., 4., 8., 7., 2., 1., 0., 4.]])
tensor([[1., 0., 1.],
        [6., 5., 4.],
        [8., 7., 2.],
        [1., 0., 4.]])
tensor([[[1., 0., 1.],
         [6., 5., 4.]],

        [[8., 7., 2.],
         [1., 0., 4.]]])
tensor([1., 0., 1., 6., 5., 4., 8., 7., 2., 1., 0., 4.])
tensor([1., 0., 1., 6., 5., 4., 8., 7., 2., 1., 0., 4.])
tensor([[1.],
        [0.],
        [1.],
        [6.],
        [5.],
        [4.],
        [8.],
        [7.],
        [2.],
        [1.],
        [0.],
        [4.]])
tensor([[1., 0., 1., 6., 5., 4., 8., 7., 2., 1., 0., 4.]])


In [30]:
# Concatenation (all dims must be same except dim)
t1 = torch.tensor([
    [1,2],
    [3,4]
])

t2 = torch.tensor([
    [5,6],
    [7,8],
])

print(torch.cat((t1, t2), dim=0), torch.cat((t1, t2), dim=0).shape) #along rows 
print(torch.cat((t1, t2), dim=1), torch.cat((t1, t2), dim=1).shape) #along columns

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]) torch.Size([4, 2])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]]) torch.Size([2, 4])


#### Working with CNN

In [54]:
# Say we've 3 images of 4x4
img = torch.rand(3,4,4)
img

tensor([[[0.7333, 0.5122, 0.7753, 0.0173],
         [0.9667, 0.5604, 0.1653, 0.8452],
         [0.1223, 0.0436, 0.3820, 0.8861],
         [0.3424, 0.1746, 0.4871, 0.3199]],

        [[0.6535, 0.2321, 0.0108, 0.5431],
         [0.2511, 0.0877, 0.5980, 0.4096],
         [0.9545, 0.9060, 0.3269, 0.1480],
         [0.8392, 0.3641, 0.4413, 0.6219]],

        [[0.8892, 0.9692, 0.7900, 0.5730],
         [0.5718, 0.1975, 0.9567, 0.1934],
         [0.7268, 0.6221, 0.0131, 0.9334],
         [0.7215, 0.9250, 0.9192, 0.5642]]])

In [46]:
# We want to add channel dimension (channel first)
img = img.reshape(3,1,4,4)
img

tensor([[[[0.8456, 0.8930, 0.8963, 0.1004],
          [0.6906, 0.9467, 0.6855, 0.1087],
          [0.6575, 0.3361, 0.7960, 0.9133],
          [0.6898, 0.3938, 0.6714, 0.3909]]],


        [[[0.7562, 0.2515, 0.7144, 0.7035],
          [0.9623, 0.0396, 0.7433, 0.2672],
          [0.3591, 0.4417, 0.8384, 0.9660],
          [0.1684, 0.2653, 0.7823, 0.5586]]],


        [[[0.2405, 0.5505, 0.0433, 0.2975],
          [0.4254, 0.4756, 0.0422, 0.7856],
          [0.2945, 0.2153, 0.8032, 0.1956],
          [0.2446, 0.0705, 0.3230, 0.7800]]]])

In [57]:
# PyTorch uses channels first, whereas TensorFlow user channels last
# Convert channels last image to channels first
img = np.random.rand(3,4,4,1)
print(img)
img = np.moveaxis(img, -1, 1)
print(img, img.shape)

[[[[0.56934115]
   [0.95820521]
   [0.25099581]
   [0.14312819]]

  [[0.33849178]
   [0.12566881]
   [0.87987867]
   [0.0682118 ]]

  [[0.65580585]
   [0.14582132]
   [0.52972853]
   [0.82393492]]

  [[0.0494063 ]
   [0.57666539]
   [0.98290107]
   [0.79161715]]]


 [[[0.00879947]
   [0.36219316]
   [0.41666167]
   [0.11140953]]

  [[0.49922693]
   [0.53387784]
   [0.26413302]
   [0.73376895]]

  [[0.70252488]
   [0.65052317]
   [0.3604827 ]
   [0.79248669]]

  [[0.27495483]
   [0.43089277]
   [0.72297158]
   [0.30674049]]]


 [[[0.19248517]
   [0.31134571]
   [0.35531728]
   [0.9558256 ]]

  [[0.73706336]
   [0.85456986]
   [0.28617647]
   [0.88695422]]

  [[0.23979107]
   [0.6462338 ]
   [0.09299462]
   [0.13532622]]

  [[0.5808097 ]
   [0.68338738]
   [0.06095831]
   [0.13478282]]]]
[[[[0.56934115 0.95820521 0.25099581 0.14312819]
   [0.33849178 0.12566881 0.87987867 0.0682118 ]
   [0.65580585 0.14582132 0.52972853 0.82393492]
   [0.0494063  0.57666539 0.98290107 0.79161715]]]


 [[

In [59]:
# Breakdown of batch of images
img = torch.tensor(img)
print(img[0]) #0th image
print(img[0][0]) #1st colour channel of oth image
print(img[0][0][0])#1st row of 0th image
print(img[0][0][0][0])#1st element of 0th image

tensor([[[0.5693, 0.9582, 0.2510, 0.1431],
         [0.3385, 0.1257, 0.8799, 0.0682],
         [0.6558, 0.1458, 0.5297, 0.8239],
         [0.0494, 0.5767, 0.9829, 0.7916]]], dtype=torch.float64)
tensor([[0.5693, 0.9582, 0.2510, 0.1431],
        [0.3385, 0.1257, 0.8799, 0.0682],
        [0.6558, 0.1458, 0.5297, 0.8239],
        [0.0494, 0.5767, 0.9829, 0.7916]], dtype=torch.float64)
tensor([0.5693, 0.9582, 0.2510, 0.1431], dtype=torch.float64)
tensor(0.5693, dtype=torch.float64)


In [62]:
# Flatten
# Say we want flattened images
print(img.flatten()) #everything flattened
print(img.flatten(start_dim=1)) #each image flattened
# OR
print(img.reshape(img.shape[0], -1))

tensor([0.5693, 0.9582, 0.2510, 0.1431, 0.3385, 0.1257, 0.8799, 0.0682, 0.6558,
        0.1458, 0.5297, 0.8239, 0.0494, 0.5767, 0.9829, 0.7916, 0.0088, 0.3622,
        0.4167, 0.1114, 0.4992, 0.5339, 0.2641, 0.7338, 0.7025, 0.6505, 0.3605,
        0.7925, 0.2750, 0.4309, 0.7230, 0.3067, 0.1925, 0.3113, 0.3553, 0.9558,
        0.7371, 0.8546, 0.2862, 0.8870, 0.2398, 0.6462, 0.0930, 0.1353, 0.5808,
        0.6834, 0.0610, 0.1348], dtype=torch.float64)
tensor([[0.5693, 0.9582, 0.2510, 0.1431, 0.3385, 0.1257, 0.8799, 0.0682, 0.6558,
         0.1458, 0.5297, 0.8239, 0.0494, 0.5767, 0.9829, 0.7916],
        [0.0088, 0.3622, 0.4167, 0.1114, 0.4992, 0.5339, 0.2641, 0.7338, 0.7025,
         0.6505, 0.3605, 0.7925, 0.2750, 0.4309, 0.7230, 0.3067],
        [0.1925, 0.3113, 0.3553, 0.9558, 0.7371, 0.8546, 0.2862, 0.8870, 0.2398,
         0.6462, 0.0930, 0.1353, 0.5808, 0.6834, 0.0610, 0.1348]],
       dtype=torch.float64)
tensor([[0.5693, 0.9582, 0.2510, 0.1431, 0.3385, 0.1257, 0.8799, 0.0682, 0.6