#### Installation check

In [2]:
import torch
print(torch.__version__)
print("GPU Available? {}".format(torch.cuda.is_available()))
print("CUDA Toolkit version: {}".format(torch.version.cuda))

0.4.1
GPU Available? True
CUDA Toolkit version: 9.0


#### Basic

In [2]:
import numpy as np
# Creating nd-array
x_cpu = torch.tensor([1,2,3]) #int (Factory function, better than torch.Tensor)
z = np.random.randint(1, 9, (5,4))
y_cpu = torch.tensor(z)
print(x_cpu)
print(y_cpu)

# Transfer of tensor to GPU
x_gpu = x_cpu.cuda()
y_gpu = y_cpu.cuda()
print(x_gpu)
print(y_gpu)

tensor([1, 2, 3])
tensor([[2, 6, 5, 4],
        [2, 6, 2, 4],
        [2, 4, 6, 7],
        [6, 4, 8, 6],
        [6, 7, 7, 1]], dtype=torch.int32)
tensor([1, 2, 3], device='cuda:0')
tensor([[2, 6, 5, 4],
        [2, 6, 2, 4],
        [2, 4, 6, 7],
        [6, 4, 8, 6],
        [6, 7, 7, 1]], device='cuda:0', dtype=torch.int32)


In [3]:
# Shape and Reshape
x = x_gpu
y = y_gpu
print(x.shape, y.shape)

y = y.reshape(1,20)
print(y, y.shape)

y = y.reshape(4,5)
print(y, y.shape)

torch.Size([3]) torch.Size([5, 4])
tensor([[2, 6, 5, 4, 2, 6, 2, 4, 2, 4, 6, 7, 6, 4, 8, 6, 6, 7, 7, 1]],
       device='cuda:0', dtype=torch.int32) torch.Size([1, 20])
tensor([[2, 6, 5, 4, 2],
        [6, 2, 4, 2, 4],
        [6, 7, 6, 4, 8],
        [6, 6, 7, 7, 1]], device='cuda:0', dtype=torch.int32) torch.Size([4, 5])


In [4]:
# tensor constructor
torch.Tensor()

tensor([])

In [5]:
torch.tensor(2,4)

TypeError: tensor() takes 1 positional argument but 2 were given

In [ ]:
torch.Tensor(2,4)

In [ ]:
t = torch.Tensor([1,2,3,4]) #float (Constructor)
t = t.cuda()
print(t.dtype)
print(t.device)
t

In [ ]:
print(torch.eye(3))
print(torch.zeros(3,2))
print(torch.ones(3,2))
print(torch.rand(3,2))
print(torch.randint(low=0, high=9, size=(3,2)))

In [ ]:
torch.tensor([1,2,3], dtype=torch.int32)

In [ ]:
# Which tensor?
x = np.array([1,2,3])
t1 = torch.Tensor(x) #copy
t2 = torch.tensor(x) #--||-- best
t3 = torch.as_tensor(x) #share memory ... faster better for performance
t4 = torch.from_numpy(x) #--||--

print(t1, t2, t3, t4)
x[0] = 0
x[1] = 0
x[2] = 0
print(t1, t2, t3, t4)

In [ ]:
# shape, size, num_dim, num_elements
t = torch.tensor(torch.randint(0,9,(3,4)))
print(t.shape)
print(t.size())
print(len(t.shape))
print(t.numel(), torch.tensor(t.shape).prod())

In [ ]:
# reshape, squeeze, unsqueeze 
print(t.reshape(12,1))
print(t.reshape(1,12))
print(t.reshape(4,3))
print(t.reshape(2,2,3))

print(t.reshape(12)) #similar to
print(t.reshape(12,1).squeeze()) #this #removes axis having length==1
print(t.reshape(12,1).squeeze().unsqueeze(dim=1)) #adds axis of length==1
print(t.reshape(12,1).squeeze().unsqueeze(dim=0))

In [8]:
# Concatenation (all dimensions must be same except dim)
t1 = torch.tensor([
    [1,2],
    [3,4]
])

t2 = torch.tensor([
    [5,6],
    [7,8],
])

print(torch.cat((t1, t2), dim=0), torch.cat((t1, t2), dim=0).shape) #along rows 
print(torch.cat((t1, t2), dim=1), torch.cat((t1, t2), dim=1).shape) #along columns

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]) torch.Size([4, 2])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]]) torch.Size([2, 4])


#### Working with CNN

In [ ]:
# Say we've 3 images of 4x4
img = torch.rand(3,4,4)
img

In [ ]:
# We want to add channel dimension (channel first)
img = img.reshape(3,1,4,4)
img

In [ ]:
# PyTorch uses channels first, whereas TensorFlow user channels last
# Convert channels last image to channels first
img = np.random.rand(3,4,4,1)
print(img)
img = np.moveaxis(img, -1, 1) # OR img = img.transpose((2, 0, 1))
print(img, img.shape)

In [ ]:
# Breakdown of batch of images
img = torch.tensor(img)
print(img[0]) #0th image
print(img[0][0]) #1st colour channel of oth image
print(img[0][0][0])#1st row of 0th image
print(img[0][0][0][0])#1st element of 0th image

In [ ]:
# Flatten
# Say we want flattened images
print(img.flatten()) #everything flattened
print(img.flatten(start_dim=1)) #each image flattened
# OR
print(img.reshape(img.shape[0], -1))

In [7]:
# Reduction Ops
x = torch.randint(1,9,(3,3))
print(x)
print(x.sum()) #sum of all elements
print(x.numel()) #number of elements
print(x.prod()) #product of all elements
print(x.mean()) #mean
print(x.std()) #standard deviation

tensor([[4., 5., 1.],
        [2., 3., 5.],
        [3., 4., 5.]])
tensor(32.)
9
tensor(36000.)
tensor(3.5556)
tensor(1.4240)


In [18]:
# Sum
x = torch.tensor([
    [1,1,1],
    [2,2,2],
    [3,3,3]
])
print(x.sum(dim=0)) #rows(axis 0) will be added not addition along a row
print(x.sum(dim=1)) #columns will be added

tensor([6, 6, 6])
tensor([3, 6, 9])


In [10]:
# Argmax (Outputs index location of the maximum value in a tensor)
x = torch.randint(1,9,(3,3))
print(x)
print(x.argmax()) #according to flattened tensor

tensor([[2., 8., 2.],
        [1., 1., 8.],
        [6., 2., 4.]])
tensor(1)


In [12]:
# Conversion
x = torch.tensor([3])
print(x)
print(x.item()) #Only scalar tensor

x = torch.tensor([1,2,3])
print(x)
print(x.tolist()) #Python list
print(type(x.numpy())) #numpy array

tensor([3])
3
tensor([1, 2, 3])
[1, 2, 3]
<class 'numpy.ndarray'>
